[package]
name = "bind9-api-client"
version = "0.1.3"
authors = ["Valentin Brandl <vbrandl@riseup.net>"]
description = "Client for the BIND9 API"
license = "MIT/Apache-2.0"

[dependencies]
clap = "2.32.0"
crypto = { path = "../crypto" }
data = { path = "../data" }
failure = "0.1.1"
hyper = "0.12"
log = "0.4.6"
openssl-probe = "0.1.2"
pretty_env_logger = "0.2.3"
reqwest = "0.8.6"
serde = "1.0.91"
serde_derive = "1.0.69"
serde_json = "1.0.27"
toml = "0.4.6"
